refac

diff --git a/bin/_nx_create b/bin/_nx_create
--- a/bin/_nx_create
+++ b/bin/_nx_create
@@ -1,14 +1,17 @@
 main() {
   local name="$1"
-  local full_script_name=create/$name.sh
-  local file_path=$devscript_path/src/$full_script_name
   if [ -z $name ]; then
     echo " usage: nex create <module>"
-  elif [ -f $file_path ]; then
-    echo " Running script: $full_script_name"
+    exit 1
+  fi
+  local full_script_name=create/$name.sh
+  local file_path=$devscript_path/src/$full_script_name
+
+  if [ -f $file_path ]; then
+    echo " Running script: $file_path"
     bash  $file_path "${@:2}"
   else
-    echo " script not found: $full_script_name"
+    echo " script not found: $file_path"
   fi
 }
 
